# Generated by Django 4.2.15 on 2024-09-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_address_line_1_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
