# Generated by Django 4.2.15 on 2024-10-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_category_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="vendor",
        ),
    ]
